using Application.Contracts;
using Domain.Entities.Production;
using Domain.Entities.Warehouse;
using Domain.Implementations.ReferenceFormat;
using Microsoft.Extensions.Logging;

namespace Application.Services.Production;

public class WorkOrderPhaseCloseHandler(
    IUnitOfWork unitOfWork,
    ILogger<WorkOrderPhaseCloseHandler> logger) : IWorkOrderPhaseCloseHandler
{
    public async Task HandlePhaseClose(WorkOrderPhaseCloseRequest request)
    {
        // 1. Obtenir la fase i els seus detalls
        var phase = await unitOfWork.WorkOrders.Phases.Get(request.WorkOrderPhaseId);
        if (phase == null)
        {
            logger.LogWarning("Fase {PhaseId} no trobada, no es processa tancament", request.WorkOrderPhaseId);
            return;
        }

        // Ignorar fases de treball extern
        if (phase.IsExternalWork)
        {
            logger.LogInformation("Fase {PhaseId} es treball extern, no es generen tiquets", request.WorkOrderPhaseId);
            return;
        }

        var phaseDetails = unitOfWork.WorkOrders.Phases.Details
            .Find(d => d.WorkOrderPhaseId == request.WorkOrderPhaseId)
            .ToList();

        if (phaseDetails.Count == 0)
        {
            logger.LogWarning("Fase {PhaseId} no te detalls, no es generen tiquets", request.WorkOrderPhaseId);
            return;
        }

        // 2. Eliminar tiquets auto-generats anteriors i obtenir els seus totals
        var removedTotals = await RemoveExistingAutoGeneratedParts(request.WorkOrderPhaseId);

        // 3. Obtenir tots els WorkcenterShiftDetail tancats per aquesta fase (tots els centres de treball)
        var shiftDetails = unitOfWork.WorkcenterShifts.Details
            .Find(d => d.WorkOrderPhaseId == request.WorkOrderPhaseId
                     && d.EndTime != null
                     && !d.Disabled)
            .ToList();

        if (shiftDetails.Count == 0)
        {
            // Still need to update WorkOrder if we removed parts
            if (removedTotals != null)
                await ApplyWorkOrderTotals(phase.WorkOrderId, null, removedTotals);

            logger.LogInformation("Fase {PhaseId} no te detalls de torn, no es generen tiquets", request.WorkOrderPhaseId);
            return;
        }

        // 4a. Flujo A: agrupar per (WorkcenterShiftId, MachineStatusId, OperatorId) - detalls amb operari
        var groupsWithOperator = shiftDetails
            .Where(d => d.OperatorId.HasValue)
            .GroupBy(d => new { d.WorkcenterShiftId, d.MachineStatusId, OperatorId = d.OperatorId!.Value });

        // 4b. Flujo B: agrupar per (WorkcenterShiftId, MachineStatusId) - detalls sense operari
        var groupsWithoutOperator = shiftDetails
            .Where(d => !d.OperatorId.HasValue)
            .GroupBy(d => new { d.WorkcenterShiftId, d.MachineStatusId });

        // Build all ProductionParts first, then persist in batch
        var partsToCreate = new List<ProductionPart>();

        // --- Flujo A: detalls amb operari ---
        foreach (var group in groupsWithOperator)
        {
            // 5. Trobar el WorkOrderPhaseDetail corresponent per MachineStatusId
            var phaseDetail = phaseDetails
                .FirstOrDefault(pd => pd.MachineStatusId == group.Key.MachineStatusId);

            if (phaseDetail == null)
            {
                logger.LogDebug(
                    "No s'ha trobat detall de fase per MachineStatusId {StatusId} a la fase {PhaseId}, s'omet",
                    group.Key.MachineStatusId, request.WorkOrderPhaseId);
                continue;
            }

            // 6. Agregar temps i quantitats
            decimal workcenterTime = 0;
            decimal operatorTime = 0;
            decimal quantity = 0;
            decimal weightedOperatorCostSum = 0;
            decimal weightedWorkcenterCostSum = 0;
            decimal totalDuration = 0;
            DateTime? minStartTime = null;

            foreach (var detail in group)
            {
                var duration = (decimal)(detail.EndTime!.Value - detail.StartTime).TotalMinutes;
                if (duration <= 0) continue;

                workcenterTime += duration;

                var concurrentOperators = detail.ConcurrentOperatorWorkcenters > 0
                    ? detail.ConcurrentOperatorWorkcenters : 1;
                operatorTime += duration / concurrentOperators;

                quantity += detail.QuantityOk;

                // Cost ponderat pel temps
                weightedOperatorCostSum += detail.OperatorCost * duration;
                weightedWorkcenterCostSum += detail.WorkcenterCost * duration;
                totalDuration += duration;

                // Track minimum StartTime for Date field
                if (minStartTime == null || detail.StartTime < minStartTime)
                    minStartTime = detail.StartTime;
            }

            if (totalDuration <= 0) continue;

            // Cost horari ponderat per temps
            var weightedOperatorHourCost = weightedOperatorCostSum / totalDuration;
            var weightedMachineHourCost = weightedWorkcenterCostSum / totalDuration;

            // Determinar el WorkcenterId a partir dels detalls del grup
            var workcenterId = await GetWorkcenterIdFromShiftDetail(group.First());

            // 7. Crear el ProductionPart
            partsToCreate.Add(new ProductionPart
            {
                Id = Guid.NewGuid(),
                Date = minStartTime ?? request.ClosedAt,
                WorkcenterId = workcenterId,
                WorkOrderId = phase.WorkOrderId,
                WorkOrderPhaseId = request.WorkOrderPhaseId,
                WorkOrderPhaseDetailId = phaseDetail.Id,
                OperatorId = group.Key.OperatorId,
                Quantity = (int)quantity,
                OperatorTime = Math.Round(operatorTime, 2),
                WorkcenterTime = Math.Round(workcenterTime, 2),
                OperatorHourCost = Math.Round(weightedOperatorHourCost, 4),
                MachineHourCost = Math.Round(weightedMachineHourCost, 4),
                IsAutoGenerated = true
            });
        }

        // --- Flujo B: detalls sense operari (OperatorTime = 0) ---
        foreach (var group in groupsWithoutOperator)
        {
            var phaseDetail = phaseDetails
                .FirstOrDefault(pd => pd.MachineStatusId == group.Key.MachineStatusId);

            if (phaseDetail == null)
            {
                logger.LogDebug(
                    "No s'ha trobat detall de fase per MachineStatusId {StatusId} a la fase {PhaseId} (sense operari), s'omet",
                    group.Key.MachineStatusId, request.WorkOrderPhaseId);
                continue;
            }

            decimal workcenterTime = 0;
            decimal quantity = 0;
            decimal weightedWorkcenterCostSum = 0;
            decimal totalDuration = 0;
            DateTime? minStartTime = null;

            foreach (var detail in group)
            {
                var duration = (decimal)(detail.EndTime!.Value - detail.StartTime).TotalMinutes;
                if (duration <= 0) continue;

                workcenterTime += duration;
                quantity += detail.QuantityOk;

                weightedWorkcenterCostSum += detail.WorkcenterCost * duration;
                totalDuration += duration;

                if (minStartTime == null || detail.StartTime < minStartTime)
                    minStartTime = detail.StartTime;
            }

            if (totalDuration <= 0) continue;

            var weightedMachineHourCost = weightedWorkcenterCostSum / totalDuration;
            var workcenterId = await GetWorkcenterIdFromShiftDetail(group.First());

            partsToCreate.Add(new ProductionPart
            {
                Id = Guid.NewGuid(),
                Date = minStartTime ?? request.ClosedAt,
                WorkcenterId = workcenterId,
                WorkOrderId = phase.WorkOrderId,
                WorkOrderPhaseId = request.WorkOrderPhaseId,
                WorkOrderPhaseDetailId = phaseDetail.Id,
                OperatorId = null,
                Quantity = (int)quantity,
                OperatorTime = 0,
                WorkcenterTime = Math.Round(workcenterTime, 2),
                OperatorHourCost = 0,
                MachineHourCost = Math.Round(weightedMachineHourCost, 4),
                IsAutoGenerated = true
            });
        }

        if (partsToCreate.Count == 0)
        {
            // Still need to update WorkOrder if we removed parts
            if (removedTotals != null)
                await ApplyWorkOrderTotals(phase.WorkOrderId, null, removedTotals);

            logger.LogInformation("Fase {PhaseId} no te grups amb temps valid, no es generen tiquets", request.WorkOrderPhaseId);
            return;
        }

        // 8. Persist all parts
        await unitOfWork.ProductionParts.AddRange(partsToCreate);

        // 9. Single WorkOrder update: subtract removed totals + add new totals + recalculate material cost
        await ApplyWorkOrderTotals(phase.WorkOrderId, partsToCreate, removedTotals);

        logger.LogInformation(
            "Generats {Count} tiquets de produccio per la fase {PhaseId}",
            partsToCreate.Count, request.WorkOrderPhaseId);
    }

    /// <summary>
    /// Removes existing auto-generated parts from the database and returns their
    /// aggregated totals (to be subtracted from WorkOrder later).
    /// Does NOT touch the WorkOrder — caller is responsible for that.
    /// </summary>
    private async Task<PartTotals?> RemoveExistingAutoGeneratedParts(Guid workOrderPhaseId)
    {
        var existingParts = unitOfWork.ProductionParts
            .Find(pp => pp.WorkOrderPhaseId == workOrderPhaseId && pp.IsAutoGenerated)
            .ToList();

        if (existingParts.Count == 0) return null;

        // Aggregate totals in memory (untracked data)
        var totals = new PartTotals();
        foreach (var part in existingParts)
        {
            totals.OperatorTime += part.OperatorTime;
            totals.MachineTime += part.WorkcenterTime;
            totals.TotalQuantity += part.Quantity;
            totals.MachineCost += (part.WorkcenterTime / 60) * part.MachineHourCost;
            totals.OperatorCost += (part.OperatorTime / 60) * part.OperatorHourCost;
        }

        // Clear navigation properties before RemoveRange to avoid EF tracking conflicts.
        // ProductionPartRepository.Find() eagerly loads WorkOrder, WorkOrderPhase, etc.
        // If multiple parts reference the same WorkOrder, RemoveRange's graph attachment
        // would try to track duplicate WorkOrder instances, causing IdentityConflict.
        foreach (var part in existingParts)
        {
            part.WorkOrder = null;
            part.WorkOrderPhase = null;
            part.WorkOrderPhaseDetail = null;
            part.Workcenter = null;
            part.Operator = null;
        }

        // Remove all auto-generated parts in one batch
        await unitOfWork.ProductionParts.RemoveRange(existingParts);

        logger.LogInformation(
            "Eliminats {Count} tiquets auto-generats anteriors per la fase {PhaseId}",
            existingParts.Count, workOrderPhaseId);

        return totals;
    }

    /// <summary>
    /// Single WorkOrder fetch + update that subtracts removed totals, adds new part totals,
    /// and recalculates material cost from all CONSUMPTION movements across all phases.
    /// By doing a single Get/Update cycle, we avoid EF tracking conflicts.
    /// </summary>
    private async Task ApplyWorkOrderTotals(Guid workOrderId, List<ProductionPart>? addedParts, PartTotals? removedTotals)
    {
        var workOrder = await unitOfWork.WorkOrders.Get(workOrderId);
        if (workOrder == null) return;

        // Subtract removed part totals
        if (removedTotals != null)
        {
            workOrder.OperatorTime -= removedTotals.OperatorTime;
            workOrder.MachineTime -= removedTotals.MachineTime;
            workOrder.TotalQuantity -= removedTotals.TotalQuantity;
            workOrder.MachineCost -= removedTotals.MachineCost;
            workOrder.OperatorCost -= removedTotals.OperatorCost;
        }

        // Add new part totals
        if (addedParts != null)
        {
            foreach (var part in addedParts)
            {
                workOrder.OperatorTime += part.OperatorTime;
                workOrder.MachineTime += part.WorkcenterTime;
                workOrder.TotalQuantity += part.Quantity;
                workOrder.MachineCost += (part.WorkcenterTime / 60) * part.MachineHourCost;
                workOrder.OperatorCost += (part.OperatorTime / 60) * part.OperatorHourCost;                                
            }
        }

        // Recalculate material cost from all CONSUMPTION movements (idempotent full replacement)
        workOrder.MaterialCost = await CalculateWorkOrderMaterialCost(workOrderId);

        await unitOfWork.WorkOrders.Update(workOrder);
    }

    /// <summary>
    /// Calculates the total material cost for a WorkOrder by summing costs from all
    /// CONSUMPTION-type StockMovements across all its phases.
    /// 
    /// Negative-quantity movements represent consumed material (cost added).
    /// Positive-quantity movements represent returned material (cost subtracted).
    /// The net result is the actual material cost.
    /// 
    /// Cost formulas (matching MetricsService):
    /// - UNITATS: cost = |Quantity| * Reference.LastCost
    /// - PLACA/RODO/TUB: cost = |Quantity| * UnitWeight * Reference.LastCost
    ///   where UnitWeight is calculated from dimensions + ReferenceType.Density
    /// </summary>
    private async Task<decimal> CalculateWorkOrderMaterialCost(Guid workOrderId)
    {
        // Get all phase IDs for this WorkOrder
        var phaseIds = unitOfWork.WorkOrders.Phases
            .Find(p => p.WorkOrderId == workOrderId)
            .Select(p => p.Id)
            .ToList();

        if (phaseIds.Count == 0) return 0;

        // Get all CONSUMPTION movements across all phases
        var consumptionMovements = unitOfWork.StockMovements
            .Find(m => m.Entity == StockMovementEntities.WorkOrderPhase
                     && m.EntityId.HasValue
                     && phaseIds.Contains(m.EntityId.Value)
                     && m.MovementType == StockMovementType.CONSUMPTION)
            .ToList();

        if (consumptionMovements.Count == 0) return 0;

        // Cache Reference/ReferenceType/ReferenceFormat lookups to avoid repeated DB hits
        var referenceCache = new Dictionary<Guid, (decimal LastCost, string FormatCode, decimal Density)>();

        decimal totalMaterialCost = 0;

        foreach (var movement in consumptionMovements)
        {
            if (!referenceCache.TryGetValue(movement.ReferenceId, out var refData))
            {
                var reference = await unitOfWork.References.Get(movement.ReferenceId);
                if (reference == null) continue;

                string formatCode = "UNITATS";
                decimal density = 0;

                if (reference.ReferenceFormatId.HasValue)
                {
                    var format = await unitOfWork.ReferenceFormats.Get(reference.ReferenceFormatId.Value);
                    if (format != null) formatCode = format.Code;
                }

                if (reference.ReferenceTypeId.HasValue)
                {
                    var referenceType = await unitOfWork.ReferenceTypes.Get(reference.ReferenceTypeId.Value);
                    if (referenceType != null) density = referenceType.Density;
                }

                refData = (reference.LastCost, formatCode, density);
                referenceCache[movement.ReferenceId] = refData;
            }

            decimal movementCost;

            if (refData.FormatCode == "UNITATS")
            {
                // UNITATS: cost = |Quantity| * LastCost
                movementCost = Math.Abs(movement.Quantity) * refData.LastCost;
            }
            else
            {
                // Dimensional (PLACA/RODO/TUB): calculate unit weight, then cost = |Quantity| * UnitWeight * LastCost
                var calculator = ReferenceFormatCalculationFactory.Create(refData.FormatCode);
                var dimensions = new ReferenceDimensions
                {
                    Quantity = Math.Abs(movement.Quantity),
                    Width = movement.Width,
                    Length = movement.Length,
                    Height = movement.Height,
                    Diameter = movement.Diameter,
                    Thickness = movement.Thickness,
                    Density = refData.Density
                };

                try
                {
                    var unitWeight = Math.Round(calculator.Calculate(dimensions), 2);
                    movementCost = Math.Abs(movement.Quantity) * unitWeight * refData.LastCost;
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex,
                        "Error calculant pes per moviment {MovementId} (Ref: {ReferenceId}, Format: {Format}), s'omet",
                        movement.Id, movement.ReferenceId, refData.FormatCode);
                    continue;
                }
            }

            // Negative quantity = consumed (add cost), positive quantity = returned (subtract cost)
            if (movement.Quantity < 0)
                totalMaterialCost += movementCost;
            else
                totalMaterialCost -= movementCost;
        }

        // Ensure we never return negative material cost
        return Math.Max(0, Math.Round(totalMaterialCost, 2));
    }

    private async Task<Guid> GetWorkcenterIdFromShiftDetail(WorkcenterShiftDetail shiftDetail)
    {
        var workcenterShift = await unitOfWork.WorkcenterShifts.Get(shiftDetail.WorkcenterShiftId);
        return workcenterShift?.WorkcenterId ?? Guid.Empty;
    }

    /// <summary>
    /// Simple POCO to carry aggregated totals without involving EF tracking.
    /// </summary>
    private class PartTotals
    {
        public decimal OperatorTime { get; set; }
        public decimal MachineTime { get; set; }
        public int TotalQuantity { get; set; }
        public decimal MachineCost { get; set; }
        public decimal OperatorCost { get; set; }
    }
}
